import { input, select, confirm, checkbox, password } from '@inquirer/prompts';
import chalk from 'chalk';
import path from 'path';
import fs from 'fs';

// ─── Types ───────────────────────────────────────────────────────────────────

interface OnboardConfig {
  llmProvider: 'openai' | 'gemini' | 'ollama';
  llmModel: string;
  openaiApiKey?: string;
  openaiBaseUrl?: string;
  geminiApiKey?: string;
  ollamaBaseUrl?: string;
  ollamaModel?: string;
  embedSameProvider: boolean;
  embedProvider?: 'openai' | 'gemini' | 'ollama';
  embedModel?: string;
  embedApiKey?: string;
  embedBaseUrl?: string;
  rerankModel?: string;
  executionMode: 'local' | 'cloud' | 'hybrid';
  cloudApiKey?: string;
  cloudGatewayUrl?: string;
  disabledSkills: string[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function printBanner() {
  console.log('');
  console.log(chalk.cyan.bold('  ╔══════════════════════════════════════════════════════╗'));
  console.log(chalk.cyan.bold('  ║') + chalk.white.bold('        🐙  AgentOctopus  — Setup Wizard             ') + chalk.cyan.bold('║'));
  console.log(chalk.cyan.bold('  ╚══════════════════════════════════════════════════════╝'));
  console.log('');
  console.log(chalk.gray('  This wizard will help you configure AgentOctopus.'));
  console.log(chalk.gray('  You can re-run it anytime with: ') + chalk.yellow('octopus onboard'));
  console.log('');
}

function printStep(step: number, total: number, title: string) {
  console.log('');
  console.log(chalk.cyan(`  ── Step ${step}/${total}: ${title} ─────────────────────────`));
  console.log('');
}

function discoverSkills(rootDir: string): Array<{ name: string; description: string }> {
  const skillsDir = path.join(rootDir, 'registry', 'skills');
  if (!fs.existsSync(skillsDir)) return [];

  const skills: Array<{ name: string; description: string }> = [];

  for (const entry of fs.readdirSync(skillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;

    const skillMdPath = path.join(skillsDir, entry.name, 'SKILL.md');
    if (!fs.existsSync(skillMdPath)) continue;

    const content = fs.readFileSync(skillMdPath, 'utf8');
    const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
    let description = entry.name;

    if (fmMatch) {
      const descLine = fmMatch[1]!.split('\n').find((l) => l.startsWith('description:'));
      if (descLine) {
        description = descLine.slice('description:'.length).trim();
      }
    }

    skills.push({ name: entry.name, description });
  }

  return skills;
}

function generateEnvContent(config: OnboardConfig): string {
  const lines: string[] = [
    '# ──────────────────────────────────────────────────────────',
    '# AgentOctopus Configuration',
    `# Generated by \`octopus onboard\` on ${new Date().toISOString()}`,
    '# ──────────────────────────────────────────────────────────',
    '',
    '# LLM Provider',
    `LLM_PROVIDER=${config.llmProvider}`,
    `LLM_MODEL=${config.llmModel}`,
  ];

  if (config.llmProvider === 'openai') {
    lines.push(`OPENAI_API_KEY=${config.openaiApiKey || ''}`);
    lines.push(`OPENAI_BASE_URL=${config.openaiBaseUrl || 'https://api.openai.com/v1'}`);
  }

  if (config.llmProvider === 'gemini' || config.geminiApiKey) {
    lines.push(`GEMINI_API_KEY=${config.geminiApiKey || ''}`);
  }

  if (config.llmProvider === 'ollama') {
    lines.push(`OLLAMA_BASE_URL=${config.ollamaBaseUrl || 'http://localhost:11434'}`);
    lines.push(`OLLAMA_MODEL=${config.ollamaModel || 'llama3.2'}`);
  }

  lines.push('');
  lines.push('# Embeddings');

  const ep = config.embedSameProvider ? config.llmProvider : (config.embedProvider || config.llmProvider);
  lines.push(`EMBED_PROVIDER=${ep}`);
  lines.push(`EMBED_MODEL=${config.embedModel || 'text-embedding-3-small'}`);

  if (!config.embedSameProvider) {
    lines.push(`EMBED_API_KEY=${config.embedApiKey || ''}`);
    lines.push(`EMBED_BASE_URL=${config.embedBaseUrl || ''}`);
  } else {
    // Reuse LLM keys
    if (config.llmProvider === 'openai') {
      lines.push(`EMBED_API_KEY=${config.openaiApiKey || ''}`);
      lines.push(`EMBED_BASE_URL=${config.openaiBaseUrl || 'https://api.openai.com/v1'}`);
    } else if (config.llmProvider === 'gemini') {
      lines.push(`EMBED_API_KEY=${config.geminiApiKey || ''}`);
    }
  }

  lines.push(`RERANK_MODEL=${config.rerankModel || config.llmModel}`);

  lines.push('');
  lines.push('# Execution Mode');
  lines.push(`EXECUTION_MODE=${config.executionMode}`);

  if (config.executionMode === 'cloud' || config.executionMode === 'hybrid') {
    lines.push(`CLOUD_GATEWAY_URL=${config.cloudGatewayUrl || 'https://api.agentoctopus.dev'}`);
    lines.push(`CLOUD_API_KEY=${config.cloudApiKey || ''}`);
  }

  lines.push('');
  lines.push('# Registry');
  lines.push('REGISTRY_PATH=./registry/skills');
  lines.push('RATINGS_PATH=./registry/ratings.json');

  if (config.disabledSkills.length > 0) {
    lines.push(`DISABLED_SKILLS=${config.disabledSkills.join(',')}`);
  }

  lines.push('');
  return lines.join('\n');
}

// ─── Main ────────────────────────────────────────────────────────────────────

export async function runOnboarding(rootDir?: string): Promise<void> {
  const root = rootDir || process.env.OCTOPUS_ROOT || process.cwd();
  const envPath = path.join(root, '.env');
  const totalSteps = 5;

  printBanner();

  // Check if .env already exists
  if (fs.existsSync(envPath)) {
    const overwrite = await confirm({
      message: chalk.yellow('An .env file already exists. Overwrite it?'),
      default: false,
    });

    if (!overwrite) {
      console.log(chalk.gray('\n  Keeping existing .env. Exiting setup.\n'));
      return;
    }
  }

  const config: OnboardConfig = {
    llmProvider: 'openai',
    llmModel: 'gpt-4o',
    embedSameProvider: true,
    executionMode: 'local',
    disabledSkills: [],
  };

  // ── Step 1: LLM Provider ────────────────────────────────────────────────

  printStep(1, totalSteps, 'LLM Provider');

  config.llmProvider = await select({
    message: 'Select your LLM provider:',
    choices: [
      {
        value: 'openai' as const,
        name: '🔵  OpenAI (or compatible API like Azure, ChatAnywhere)',
        description: 'GPT-4o, GPT-4o-mini, and compatible endpoints',
      },
      {
        value: 'gemini' as const,
        name: '🟡  Google Gemini',
        description: 'Gemini Pro, Ultra, Flash',
      },
      {
        value: 'ollama' as const,
        name: '🟢  Ollama (Local)',
        description: 'Run LLMs locally — Llama, Mistral, etc.',
      },
    ],
  });

  if (config.llmProvider === 'openai') {
    config.openaiApiKey = await password({
      message: 'OpenAI API Key (sk-...):',
      mask: '*',
      validate: (v) => (v.length > 0 ? true : 'API Key is required'),
    });

    config.openaiBaseUrl = await input({
      message: 'Base URL:',
      default: 'https://api.openai.com/v1',
    });

    config.llmModel = await input({
      message: 'Model name:',
      default: 'gpt-4o-mini',
    });
  } else if (config.llmProvider === 'gemini') {
    config.geminiApiKey = await password({
      message: 'Gemini API Key:',
      mask: '*',
      validate: (v) => (v.length > 0 ? true : 'API Key is required'),
    });

    config.llmModel = await input({
      message: 'Model name:',
      default: 'gemini-2.0-flash',
    });
  } else if (config.llmProvider === 'ollama') {
    config.ollamaBaseUrl = await input({
      message: 'Ollama base URL:',
      default: 'http://localhost:11434',
    });

    config.ollamaModel = await input({
      message: 'Model name:',
      default: 'llama3.2',
    });

    config.llmModel = config.ollamaModel;
  }

  // ── Step 2: Embeddings ─────────────────────────────────────────────────

  printStep(2, totalSteps, 'Embedding Configuration');

  config.embedSameProvider = await confirm({
    message: `Use same provider (${config.llmProvider}) for embeddings?`,
    default: true,
  });

  if (!config.embedSameProvider) {
    config.embedProvider = await select({
      message: 'Select embedding provider:',
      choices: [
        { value: 'openai' as const, name: '🔵  OpenAI' },
        { value: 'gemini' as const, name: '🟡  Google Gemini' },
        { value: 'ollama' as const, name: '🟢  Ollama (Local)' },
      ],
    });

    if (config.embedProvider === 'openai') {
      config.embedApiKey = await password({
        message: 'Embedding API Key:',
        mask: '*',
      });

      config.embedBaseUrl = await input({
        message: 'Embedding Base URL:',
        default: 'https://api.openai.com/v1',
      });
    } else if (config.embedProvider === 'gemini') {
      config.embedApiKey = await password({
        message: 'Gemini API Key for embeddings:',
        mask: '*',
      });
    } else if (config.embedProvider === 'ollama') {
      config.embedBaseUrl = await input({
        message: 'Ollama base URL for embeddings:',
        default: config.ollamaBaseUrl || 'http://localhost:11434',
      });
    }
  }

  config.embedModel = await input({
    message: 'Embedding model name:',
    default: 'text-embedding-3-small',
  });

  config.rerankModel = await input({
    message: 'Rerank model (used for final skill selection):',
    default: config.llmModel || 'gpt-4o-mini',
  });

  // ── Step 3: Execution Mode ─────────────────────────────────────────────

  printStep(3, totalSteps, 'Execution Mode');

  config.executionMode = await select({
    message: 'Where should skills execute?',
    choices: [
      {
        value: 'local' as const,
        name: '💻  Local only — all skills run on your machine',
        description: 'Best for development and privacy',
      },
      {
        value: 'cloud' as const,
        name: '☁️   Cloud only — use AgentOctopus Cloud',
        description: 'No local setup needed, requires API key',
      },
      {
        value: 'hybrid' as const,
        name: '🔄  Hybrid — prefer local, fallback to cloud',
        description: 'Best of both worlds',
      },
    ],
  });

  if (config.executionMode === 'cloud' || config.executionMode === 'hybrid') {
    config.cloudGatewayUrl = await input({
      message: 'Cloud gateway URL:',
      default: 'https://api.agentoctopus.dev',
    });

    config.cloudApiKey = await password({
      message: 'Cloud API Key (leave empty to use free tier):',
      mask: '*',
    });

    if (!config.cloudApiKey) {
      console.log(chalk.gray('\n  ℹ  No Cloud API Key provided.'));
      console.log(chalk.gray('     You can register for a free key at:'));
      console.log(chalk.cyan('     https://api.agentoctopus.dev/register\n'));
    }
  }

  // ── Step 4: Skill Selection ────────────────────────────────────────────

  printStep(4, totalSteps, 'Skill Selection');

  const availableSkills = discoverSkills(root);

  if (availableSkills.length === 0) {
    console.log(chalk.gray('  No skills found in registry. Skipping skill selection.'));
    console.log(chalk.gray('  You can install skills later with: ') + chalk.yellow('octopus add <skill>'));
  } else {
    const enabledSkills = await checkbox({
      message: 'Select skills to enable:',
      choices: availableSkills.map((s) => ({
        value: s.name,
        name: `${s.name} — ${chalk.gray(s.description)}`,
        checked: true,
      })),
    });

    config.disabledSkills = availableSkills
      .map((s) => s.name)
      .filter((name) => !enabledSkills.includes(name));
  }

  // ── Step 5: Review & Save ──────────────────────────────────────────────

  printStep(5, totalSteps, 'Review & Save');

  console.log(chalk.white.bold('  Configuration Summary:'));
  console.log('');
  console.log(`  ${chalk.gray('LLM Provider:')}    ${chalk.cyan(config.llmProvider)}`);
  console.log(`  ${chalk.gray('LLM Model:')}       ${chalk.cyan(config.llmModel)}`);
  console.log(`  ${chalk.gray('Embed Provider:')}   ${chalk.cyan(config.embedSameProvider ? config.llmProvider : (config.embedProvider || config.llmProvider))}`);
  console.log(`  ${chalk.gray('Embed Model:')}      ${chalk.cyan(config.embedModel || 'text-embedding-3-small')}`);
  console.log(`  ${chalk.gray('Execution Mode:')}   ${chalk.cyan(config.executionMode)}`);

  if (availableSkills.length > 0) {
    const enabledCount = availableSkills.length - config.disabledSkills.length;
    console.log(`  ${chalk.gray('Skills:')}           ${chalk.cyan(`${enabledCount}/${availableSkills.length} enabled`)}`);

    if (config.disabledSkills.length > 0) {
      console.log(`  ${chalk.gray('Disabled:')}         ${chalk.yellow(config.disabledSkills.join(', '))}`);
    }
  }

  console.log('');

  const confirmed = await confirm({
    message: 'Save this configuration?',
    default: true,
  });

  if (!confirmed) {
    console.log(chalk.yellow('\n  Setup cancelled. No changes were made.\n'));
    return;
  }

  // Write .env
  const envContent = generateEnvContent(config);
  fs.writeFileSync(envPath, envContent, 'utf8');

  console.log('');
  console.log(chalk.green.bold('  ✅ Configuration saved to .env'));
  console.log('');
  console.log(chalk.gray('  Next steps:'));
  console.log(chalk.white('    1. ') + chalk.cyan('octopus ask "translate hello to French"') + chalk.gray('  — test routing'));
  console.log(chalk.white('    2. ') + chalk.cyan('octopus list') + chalk.gray('                               — see available skills'));
  console.log(chalk.white('    3. ') + chalk.cyan('octopus start') + chalk.gray('                              — start web UI + gateway'));
  console.log('');
}

/**
 * Check whether onboarding is needed (no .env file exists).
 * Returns true if the user completed onboarding or already has an .env.
 */
export async function ensureOnboarded(rootDir?: string): Promise<boolean> {
  const root = rootDir || process.env.OCTOPUS_ROOT || process.cwd();
  const envPath = path.join(root, '.env');

  if (fs.existsSync(envPath)) {
    return true;
  }

  console.log(chalk.yellow('\n  ⚠  No .env file found. Let\'s set up AgentOctopus first.\n'));

  const runSetup = await confirm({
    message: 'Run setup wizard now?',
    default: true,
  });

  if (runSetup) {
    await runOnboarding(root);
    return fs.existsSync(envPath);
  }

  console.log(chalk.gray('\n  You can run setup later with: ') + chalk.yellow('octopus onboard'));
  console.log(chalk.gray('  Or manually create .env from .env.example\n'));
  return false;
}
