name: PR Labeler

on:
  pull_request:
    branches:
      - master

jobs:
  label:
    name: 🏷 Auto-label PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          sync-labels: true
